# -*- coding: utf-8 -*-
"""sales_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q0Y6dqljpDyUiu898jI-3uRMPLdWJkyj

Project: Sales Data Analysis
Week: 3
Objective:
- Load sales data
- Clean missing values
- Analyze sales performance
- Generate key insights
"""

!pip install Pandas

import pandas as pd

# Step 1: Load dataset
file_path = r"/sales_data.csv"
df = pd.read_csv(file_path)

# Step 2: Display first 5 rows
print("First 5 rows of dataset:")
print(df.head())

# Step 3: Dataset basic information
print("\nDataset Information:")
print(df.info())

print("\nDataset Shape (Rows, Columns):")
print(df.shape)

# Step 4: Check missing values
print("\nMissing values in each column:")
print(df.isnull().sum())

# Step 5: Handle missing values
# Filling numeric missing values with 0
df.fillna(0, inplace=True)

# Step 6: Sales Analysis
total_revenue = df['Total_Sales'].sum()
average_sales = df['Total_Sales'].mean()
max_sales = df['Total_Sales'].max()
min_sales = df['Total_Sales'].min()

# Best-selling product
best_product = df.groupby('Product')['Total_Sales'].sum().idxmax()

# Step 7: Display results
print("\n📊 Sales Analysis Report")
print(f"Total Revenue: ₹{total_revenue:,.2f}")
print(f"Average Sales: ₹{average_sales:,.2f}")
print(f"Highest Sale Value: ₹{max_sales:,.2f}")
print(f"Lowest Sale Value: ₹{min_sales:,.2f}")
print(f"Best-Selling Product: {best_product}")

